a = input('Digite algo:')
print('o tipo primitivo desse valor é', type(a))
print('só tem espaços?',a.isnumeric())
print('É um número?', a.isnumeric())
print('é alfabético?', a.isalpha())
print('é alfanumérico?', a.isalnum())
print('Está em maiusculas?', a.isupper())
print('Está em minusculas?', a.islower())
print('Está capitalizada', a.istitle())

